apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ribollequis87/auth-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: "db"
            - name: DATABASE_USER
              value: "store"
            - name: DATABASE_PASSWORD
              value: "store"
