global:
  scrape_interval: 15s

scrape_configs:
  - job_name: product
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - product:8080

  - job_name: order
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - order:8080
